# Generated by Django 5.0.6 on 2024-06-09 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentId', models.CharField(max_length=50, unique=True)),
                ('date', models.DateTimeField(unique=True)),
                ('studentName', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=150, unique=True)),
                ('names', models.CharField(max_length=150)),
                ('course', models.CharField(choices=[('AI', 'Professional Diploma in Artificial Intelligence'), ('IT', 'Professional Diploma in Data Analytics'), ('ECE', 'Professional Diploma in Software Engineering'), ('ME', 'Professional Diploma in Blockchain Technology')], max_length=10)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
            ],
        ),
    ]
